In [1]:
import numpy as np
import pandas as pd

In [2]:
rows = 100
cols = 2
A = np.random.rand(rows, cols)
X = np.random.rand(cols)
y = A.dot(X)
A, X, y

(array([[3.18354296e-01, 5.28900653e-01],
        [8.01224709e-01, 8.19753227e-01],
        [1.93251864e-01, 7.13975793e-01],
        [5.01087320e-01, 5.34095592e-01],
        [5.61466861e-02, 6.54275786e-01],
        [5.53518951e-01, 9.67192557e-01],
        [8.18177976e-01, 5.84069210e-01],
        [8.40308458e-01, 6.33235630e-01],
        [6.59132493e-01, 8.81132924e-01],
        [5.27541308e-01, 4.41213799e-01],
        [3.70212147e-01, 4.25100708e-01],
        [5.47573441e-01, 6.12219801e-01],
        [5.80052179e-01, 4.53476822e-01],
        [2.54795603e-01, 3.25494091e-01],
        [7.81944238e-01, 3.23861266e-01],
        [6.40953148e-01, 9.88936007e-01],
        [7.92987358e-01, 8.67060735e-01],
        [2.15353501e-01, 3.01489874e-01],
        [1.19361232e-02, 8.14613319e-01],
        [3.24558827e-01, 7.60656859e-01],
        [7.81391543e-01, 6.49571679e-01],
        [8.91284529e-01, 7.02289145e-01],
        [3.99675136e-01, 7.29783453e-01],
        [8.74997502e-01, 3.3858322

In [6]:
def f_function(A, x, y):
    # Hàm f(x) - least square
    return 0.5*np.linalg.norm(A.dot(x) - y, 2)**2

def gradient(A, x, y):
    # Đạo hàm bậc 1 (vector gradident) của hàm f(x)
    return np.transpose(A).dot(A.dot(x) - y)

def backtracking_line_search(A, x_k, y, alpha_bar=1, ro=0.5, c=1e-4):
    # Tìm kiếm theo tia theo phương pháp backtracking
    # Khởi tạo các tham số alpha > 0, ro nằm trong đoạn (0,1), c nằm trong đoạn (0,1)
    alpha = alpha_bar
    
    # vector gradient tại x_k
    grad_k = gradient(A, x_k, y)
    p_k = -grad_k
    
    # giá trị hàm f() tại x_k
    f_k = f_function(A, x_k, y)
    
    # gradient tại x_k * p_k
    grad_p_k = c*np.dot(grad_k,p_k)
    
  
    while f_function(A, x_k + alpha*p_k, y) > f_k + alpha*grad_p_k:
        alpha *= ro
    # trả về giá trị alpha tại x_k
    return alpha
def gradient_descent(A, y, T):
    # m dòng (samples), n cột (features)
    m, n = A.shape
    
    # khởi tạo vector x
    x = np.zeros(n)
    
    for i in range(T):
        print('_'*50)
        print('x_k = ', x)
        # tính gradient
        grad = gradient(A, x, y)
        
        # tìm độ dài bước thỏa mãn điều kiện Wolfe thứ nhất theo 1 cách thích hợp
        # mà không cần đòi hỏi điều kiện 2
        alpha = backtracking_line_search(A, x, y)
        print('alpha_k =', alpha)
        
        x = x - alpha*grad
    return x
gradient_descent(A, y, 100)

__________________________________________________
x_k =  [0. 0.]
alpha_k = 0.015625
__________________________________________________
x_k =  [0.40654915 0.47694885]
alpha_k = 0.0625
__________________________________________________
x_k =  [0.38497149 0.48313236]
alpha_k = 0.03125
__________________________________________________
x_k =  [0.38964907 0.49798719]
alpha_k = 0.03125
__________________________________________________
x_k =  [0.3764425  0.49039291]
alpha_k = 0.03125
__________________________________________________
x_k =  [0.38291193 0.50397942]
alpha_k = 0.03125
__________________________________________________
x_k =  [0.37089013 0.49506747]
alpha_k = 0.03125
__________________________________________________
x_k =  [0.37857276 0.50789228]
alpha_k = 0.03125
__________________________________________________
x_k =  [0.36726606 0.49806595]
alpha_k = 0.03125
__________________________________________________
x_k =  [0.37578778 0.51045825]
alpha_k = 0.03125
________________

array([0.36560994, 0.50936105])

In [8]:
def f_function(A, x, y):
    # Hàm f(x) - least square
    return 0.5*np.linalg.norm(A.dot(x) - y, 2)**2

def gradient(A, x, y):
    # Đạo hàm bậc 1 (vector gradident) của hàm f(x)
    return np.transpose(A).dot(A.dot(x) - y)

def backtracking_line_search(A, x_k, y, alpha_bar=1, ro=0.5, c=1e-4):
    # Tìm kiếm theo tia theo phương pháp backtracking
    # Khởi tạo các tham số alpha > 0, ro nằm trong đoạn (0,1), c nằm trong đoạn (0,1)
    alpha = alpha_bar
    
    # vector gradient tại x_k
    grad_k = gradient(A, x_k, y)
    p_k = -grad_k
    
    # giá trị hàm f() tại x_k
    f_k = f_function(A, x_k, y)
    
    # gradient tại x_k * p_k
    grad_p_k = c*np.dot(grad_k,p_k)
    
    # cập nhật giá trị của function tại x_k
    f_new = f_function(A, x_k + alpha*p_k, y)
    #old_fval = f_k + alpha*grad_p_k
    
    while f_new > f_k + alpha*grad_p_k:
        alpha *= ro
        f_new = f_function(A, x_k + alpha*p_k, y)
    # trả về giá trị alpha, f_value tại x_k
    return alpha

def gradient_descent(A, y, T):
    # m dòng (samples), n cột (features)
    m, n = A.shape
    
    # khởi tạo vector x
    x = np.zeros(n)
    
    for i in range(T):
        print('_'*50)
        print('x_k = ', x)
        # tính gradient
        grad = gradient(A, x, y)
        
        # tìm độ dài bước thỏa mãn điều kiện Wolfe thứ nhất theo 1 cách thích hợp
        # mà không cần đòi hỏi điều kiện 2
        alpha = backtracking_line_search(A, x, y)
        print('alpha_k =', alpha)
        
        x = x - alpha*grad
    return x, i
gradient_descent(A, y, 1000)

__________________________________________________
x_k =  [0. 0.]
alpha_k = 0.015625
__________________________________________________
x_k =  [0.40654915 0.47694885]
alpha_k = 0.0625
__________________________________________________
x_k =  [0.38497149 0.48313236]
alpha_k = 0.03125
__________________________________________________
x_k =  [0.38964907 0.49798719]
alpha_k = 0.03125
__________________________________________________
x_k =  [0.3764425  0.49039291]
alpha_k = 0.03125
__________________________________________________
x_k =  [0.38291193 0.50397942]
alpha_k = 0.03125
__________________________________________________
x_k =  [0.37089013 0.49506747]
alpha_k = 0.03125
__________________________________________________
x_k =  [0.37857276 0.50789228]
alpha_k = 0.03125
__________________________________________________
x_k =  [0.36726606 0.49806595]
alpha_k = 0.03125
__________________________________________________
x_k =  [0.37578778 0.51045825]
alpha_k = 0.03125
________________

(array([0.36560994, 0.50936105]), 999)